name: Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: 21.3.0
          java: java17

      - run: |
          chmod +x gradlew
          ./gradlew clean build javadocJar sourcesJar
